app/modules/models.py
# encoding: utf-8
"""
@version: ??
@author: chenyitao
@license: Apache Licence 
@software: PyCharm
@file: models.py
@time: 2018/3/28 17:42
"""
import copy

from migrate import UniqueConstraint

from app import db


class Modules(db.Model):
    __tablename__ = 'modules'

    id = db.Column(db.Integer, primary_key=True)
    own = db.Column(db.String(16))
    platform = db.Column(db.String(32))
    feature = db.Column(db.String(32))
    package = db.Column(db.String(64))
    mould = db.Column(db.String(32))
    url = db.Column(db.String(1024))
    version = db.Column(db.String(16))
    file_md5 = db.Column(db.String(32))
    valid = db.Column(db.Boolean, default=True)
    timestamp = db.Column(db.Integer)
    __table_args__ = (UniqueConstraint('own', 'platform', 'feature', name='_own_platform_feature_uc'),)

    def update(self, new_modules):
        self.own = new_modules.own
        self.platform = new_modules.platform
        self.feature = new_modules.feature
        self.package = new_modules.package
        self.mould = new_modules.mould
        self.url = new_modules.url
        self.version = new_modules.version
        self.file_md5 = new_modules.file_md5
        self.valid = new_modules.valid
        self.timestamp = new_modules.timestamp
        db.session.commit()

    def to_dict(self):
        kws = copy.deepcopy(self.__dict__)
        del kws['_sa_instance_state']
        return kws

app/modules/forms.py
# encoding: utf-8
"""
@version: ??
@author: chenyitao
@license: Apache Licence 
@software: PyCharm
@file: forms.py
@time: 2018/3/21 15:50
"""

from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, SubmitField, FileField, RadioField, TextAreaField
from wtforms.validators import Length, DataRequired, Optional

from app import upload_set


class FileSelectForm(FlaskForm):
    modules_file = FileField(validators=[FileAllowed(upload_set, 'Python File Only!')],
                             render_kw={'multiple': 'multiple',
                                        'style': ('position:absolute; '
                                                  'filter:alpha(opacity=0);'
                                                  'opacity:0;width:30px;'),
                                        'onchange': 'display()'})
    select_files = SubmitField(u'请选择文件',
                               render_kw={'onclick': "$('#modules_file').click();",
                                          'type': "button"})
    files = StringField(render_kw={'readonly': True,
                                   'style': 'no-repeat 60px center;'})
    process_selector = RadioField('Process',
                                  validators=[Optional()],
                                  choices=[('Crawler', 'Crawler'),
                                           ('Parser', 'Parser'),
                                           ('Proxy Checker', 'Proxy')],
                                  default=1)
    platform = StringField(validators=[DataRequired(), Length(1, 32)],
                           render_kw={'class': 'input-lg'})
    submit = SubmitField(u'上传')


class FileEditForm(FlaskForm):
    code_editor = TextAreaField(validators=[DataRequired()])
    commit = SubmitField(u'提交')
    cancel = SubmitField(u'取消/返回')

app/modules/__init__.py
# encoding: utf-8
"""
@version: ??
@author: chenyitao
@license: Apache Licence 
@software: PyCharm
@file: __init__.py.py
@time: 2018/3/21 10:48
"""

from flask import Blueprint

modules = Blueprint('modules', __name__)

from . import views
from . import models
from . import forms

app/modules/views.py
# encoding: utf-8
"""
@version: ??
@author: chenyitao
@license: Apache Licence 
@software: PyCharm
@file: views.py
@time: 2018/3/21 10:49
"""
from collections import defaultdict

from flask import render_template, request, redirect, url_for, abort, flash
from flask_login import login_required

from app import upload_set, db
from .models import Modules
from .forms import FileSelectForm, FileEditForm
from .helper import get_modules_info, push_update_event
from . import modules


@modules.route('/list')
@login_required
def modules_list():
    modules_list = Modules.query.all()
    modules = defaultdict(list)
    for module in modules_list:
        modules[module.platform].append(module)
    return render_template('modules/modules_list.html', modules=modules)


@modules.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    file_select_form = FileSelectForm()
    if file_select_form.validate_on_submit():
        files = request.files.getlist('modules_file')
        platform = file_select_form.platform.data
        own = file_select_form.process_selector.data
        for _file in files:
            filename = upload_set.save(_file, name='{}/{}'.format(platform, _file.filename))
            file_url = upload_set.url(filename)
            modules, msg = get_modules_info(platform, filename, _file.stream.getvalue())
            if not modules:
                flash(msg)
                break
            modules.own = own
            modules.url = file_url
            m = Modules.query.filter_by(own=modules.own,
                                        platform=modules.platform,
                                        feature=modules.feature).first()
            if not m:
                db.session.add(modules)
                db.session.commit()
            else:
                m.update(modules)
        else:
            return redirect(url_for('modules.modules_list'))
    return render_template('modules/upload.html', file_select_form=file_select_form)


@modules.route('/<mid>/edit', methods=['POST', 'GET'])
@login_required
def edit_module(mid):
    form = FileEditForm()
    modules = Modules.query.get(int(mid))
    if not modules:
        return abort(404)
    filename = '{}/{}.py'.format(modules.platform, modules.package)
    if form.validate_on_submit():
        if request.form.get('cancel', None):
            return redirect(url_for('modules.modules_list'))
        content = form.code_editor.data
        with open('./PythonFiles/{}'.format(filename), 'w') as f:
            f.write(content.encode('utf-8'))
        upload_set.url(filename)
        new_module = get_modules_info(modules.platform, filename, content.encode('utf-8'))[0]
        new_module.id = modules.id
        new_module.own = modules.own
        new_module.url = modules.url
        modules.update(new_module)
        db.session.add(modules)
        db.session.commit()
        flash(u'修改成功!')
        return redirect(url_for('modules.edit_module', mid=mid))
    if modules:
        with open('./PythonFiles/{}'.format(filename)) as f:
            content = f.read()
            form.code_editor.data = content.decode('utf-8').lstrip()
            return render_template('modules/editor.html',
                                   filename=filename,
                                   form=form)


@modules.route('/<mid>/push')
@login_required
def push_module(mid):
    modules = Modules.query.get(int(mid))
    if not modules:
        flash(u'找不到模块信息！')
        return abort(404)
    push_update_event(modules)
    flash(u'模块更新消息推送成功！')
    return redirect(url_for('modules.modules_list'))


@modules.route('/<mid>/delete')
@login_required
def delete_module(mid):
    modules = Modules.query.get(int(mid))
    if modules:
        db.session.delete(modules)
        db.session.commit()
    return redirect(url_for('modules.modules_list', modules=Modules.query.all()))

app/templates/modules/editor.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}TDDC-Modules File Edit{% endblock %}

{% block page_content %}
<div class="page-header">
    <h2>Modules File Edit</h2>
    <span style="font-size: 20px;">File Name:</span>
    <strong>{{ filename }}</strong>
    <hr>
    {{ wtf.quick_form(form) }}
    <script src="http://ajaxorg.github.io/ace-builds/src/ace.js"></script>
    <script>
        function cerateEditor(name) {
            var textarea = document.querySelector("form textarea[name=" + name + "]");
            var editor = ace.edit();

            var theme = "clouds"
            var language = "python"
            editor.setTheme("ace/theme/" + theme);
            editor.session.setMode("ace/mode/" + language);
            if (window.innerHeight)
                winHeight = window.innerHeight;
            else if ((document.body) && (document.body.clientHeight))
                winHeight = document.body.clientHeight;
            winHeight -= 100;
            editor.container.style.height = winHeight.toString() + "px";
            editor.session.setValue(textarea.value);

            editor.setFontSize(12);
            textarea.parentNode.insertBefore(editor.container, textarea);
            textarea.style.display = "none";

            editor.setReadOnly(false);

            editor.setOption("wrap", "free")

            ace.require("ace/ext/language_tools");
            editor.setOptions({
                enableBasicAutocompletion: true,
                enableSnippets: true,
                enableLiveAutocompletion: true
            });
            var form = textarea;
            while (form && form.localName != "form") form = form.parentNode
            form.addEventListener("submit", function() {
                textarea.value = editor.getValue();
            }, true)
        }
        cerateEditor('code_editor');

    </script>
</div>
{% endblock %}

app/templates/modules/modules_list.html
{% extends "base.html" %}

{% block title %}TDDC-Modules List{% endblock %}

{% block page_content %}
<div class="page-header">
    <h2>模块列表</h2>
    <hr>
    <button type="button" class="btn btn-default">
        <a href="{{ url_for('modules.upload') }}">新增</a>
    </button>
    <hr>
    {% for platform, items in modules.items() %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{{ platform }}</h2>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th class="panel-title">ID</th>
                            <th class="panel-title">Own</th>
                            <th class="panel-title">Platform</th>
                            <th class="panel-title">Feature</th>
                            <th class="panel-title">Package</th>
                            <th class="panel-title">Mould</th>
                            <th class="panel-title">Version</th>
                            <!--<th class="panel-title">MD5</th>-->
                            <th class="panel-title">Valid</th>
                            <th class="panel-title">Timestamp</th>
                            <th class="panel-title">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for item in items %}
                        <tr>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">
                                <a href="{{ url_for('modules.edit_module', mid=item.id) }}">{{ item.id }}</a>
                            </td>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ item.own }}</td>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ item.platform }}</td>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ item.feature }}</td>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">
                                <a href="{{ item.url }}">{{ item.package }}</a>
                            </td>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ item.mould }}</td>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ item.version }}</td>
                            <!--<td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;"></td>-->
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ item.valid }}</td>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ item.timestamp }}</td>
                            <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">
                                <button type="button" class="btn btn-default">
                                    <a href="{{ url_for('modules.edit_module', mid=item.id) }}">修改</a>
                                </button>
                                <button type="button" class="btn btn-success">
                                    <a href="{{ url_for('modules.push_module', mid=item.id) }}">推送更新</a>
                                </button>
                                <button type="button" class="btn btn-danger" onclick="return delete_modules();">
                                    <a href="{{ url_for('modules.delete_module', mid=item.id) }}">删除</a>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <script>
                function delete_modules() {
                    return confirm('确认要从集群中删除此模块吗？');
                }
            </script>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/modules/upload.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}TDDC-Modules Update{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>上传模块</h1>
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {{ wtf.quick_form(file_select_form) }}
        </form>
    </div>
    {% for error in file_select_form.errors %}
        {{ error }}
    {% endfor %}
    <script>
    function display() {
        var files = document.getElementById('modules_file').files;
        var filenames_lab = document.getElementById('files');
        if (files == null | files.length == 0) {
            alert("请选择文件！");
        }
        var names = '';
        for (var i = 0; i < files.length; i++) {
            var stuff = files[i].name.match(/^(.*)(\.)(.{1,8})$/)[3];
            if (stuff != 'py') {
                alert("文件类型错误：" + files[i].name);
            }
            names += ("File" + (i+1).toString() + ": " + files[i].name + "\t");
        }
        filenames_lab.value = names;
    }
</script>
</div>
{% endblock %}