app/task/models.py
# encoding: utf-8
"""
@version: ??
@author: chenyitao
@license: Apache Licence 
@software: PyCharm
@file: models.py
@time: 2018/3/27 20:06
"""
import copy

from app import db


class TaskConfigModel(db.Model):
    __tablename__ = 'task_config'

    id = db.Column(db.Integer, primary_key=True)
    crawler_topic = db.Column(db.String(32))
    parser_topic = db.Column(db.String(32))
    cache_key_base = db.Column(db.String(32))
    status_key_base = db.Column(db.String(32))
    record_key_base = db.Column(db.String(32))
    max_queue_size = db.Column(db.Integer)


class MainTask(db.Model):
    __tablename__ = 'main_task'

    id = db.Column(db.Integer, primary_key=True)
    url = db.Column(db.String(1024))
    platform = db.Column(db.String(32))
    feature = db.Column(db.String(32))
    status = db.Column(db.Integer)
    space = db.Column(db.Integer)
    headers = db.Column(db.String(1024))
    method = db.Column(db.String(8), default='GET')
    proxy = db.Column(db.String(8), default='HTTP')
    valid = db.Column(db.Boolean, default=True)
    timestamp = db.Column(db.Integer)

    def to_dict(self):
        kws = copy.deepcopy(self.__dict__)
        del kws['_sa_instance_state']
        return kws

app/task/forms.py
# encoding: utf-8
"""
@version: ??
@author: chenyitao
@license: Apache Licence 
@software: PyCharm
@file: forms.py
@time: 2018/3/21 12:46
"""

from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, SubmitField
from wtforms.validators import Length, DataRequired, URL


class TaskForm(FlaskForm):
    id = StringField('ID', validators=[DataRequired()], render_kw={'readonly': True})

    platform = StringField('Platform', validators=[DataRequired(), Length(1, 32)])

    feature = StringField('Feature', validators=[DataRequired(), Length(1, 32)])

    url = StringField('URL', validators=[DataRequired(), Length(1, 1024), URL()])

    method = StringField('Method', validators=[DataRequired(), Length(3, 8)])

    proxy = StringField('Proxy Type', validators=[Length(0, 8)])

    space = StringField('Space',
                        validators=[DataRequired()])

    headers = StringField('Headers', validators=[Length(0, 1024)])

    valid = BooleanField('Valid')

    timestamp = StringField('Timestamp', render_kw={'readonly': True})

    submit = SubmitField(u'提交')

    def update(self, task):
        self.id.data = str(task.id)
        self.url.data = task.url
        self.platform.data = task.platform
        self.feature.data = task.feature
        self.space.data = task.space
        self.headers.data = task.headers
        self.method.data = task.method
        self.proxy.data = task.proxy
        self.valid.data = bool(task.valid)
        self.timestamp.data = task.timestamp

app/task/__init__.py
# encoding: utf-8
"""
@version: ??
@author: chenyitao
@license: Apache Licence 
@software: PyCharm
@file: __init__.py.py
@time: 2018/3/21 10:48
"""

from flask import Blueprint

task = Blueprint('task', __name__)

from . import views
from . import models

app/task/views.py
# encoding: utf-8
"""
@version: ??
@author: chenyitao
@license: Apache Licence 
@software: PyCharm
@file: views.py
@time: 2018/3/21 10:51
"""
import time
from flask import render_template, redirect, url_for
from flask_login import login_required

from app import db
from .models import MainTask
from app.task.forms import TaskForm
from . import task


@task.route('/list')
@login_required
def task_list():
    return render_template('task/task_list.html', task_list=MainTask.query.all())


@task.route('/<tid>/edit', methods=['GET', 'POST'])
@login_required
def edit_task(tid):
    main_task = MainTask.query.get(int(tid))
    form = TaskForm()
    if form.validate_on_submit():
        if not main_task:
            main_task = MainTask()
            db.session.add(main_task)
        main_task.timestamp = int(time.time())
        main_task.platform = form.platform.data
        main_task.feature = form.feature.data
        main_task.url = form.url.data
        main_task.method = form.method.data
        main_task.proxy = form.proxy.data
        main_task.space = int(form.space.data)
        main_task.headers = form.headers.data
        main_task.valid = form.valid.data
        db.session.commit()
        return redirect(url_for('task.task_list'))
    if int(tid) == -1:
        main_task = MainTask()
    form.update(main_task)
    return render_template('task/task_edit.html', form=form)


@task.route('/<tid>/delete', methods=['GET', 'POST'])
@login_required
def delete_task(tid):
    main_task = MainTask.query.get(int(tid))
    if main_task:
        db.session.delete(main_task)
        db.session.commit()
    return redirect(url_for('task.task_list'))

app/templates/task/task_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}TDDC-Task Edit{% endblock%}

{% block page_content %}
<div class="page-header">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/task/task_list.html
{% extends "base.html" %}

{% block title %}TDDC-Task List{% endblock%}

{% block page_content %}
<div class="page-header">
    <h1>任务列表</h1>
    <button type="button" class="btn btn-default">
        <a href="{{ url_for('task.edit_task', tid='-1') }}">新增</a>
    </button>
    <div class="table-responsive">
        <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Platform</th>
                <th>Feature</th>
                <th>URL</th>
                <th>Method</th>
                <th>Space</th>
                <th>Headers</th>
                <th>Proxy</th>
                <th>Valid</th>
                <th>Timestamp</th>
                <th>Action</th>
            </tr>
        </thead>
        {% for task in task_list %}
        <tbody>
            <tr>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">
                    <a href="{{ url_for('task.edit_task', tid=task.id) }}">{{ task.id }}
                </td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.platform }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.feature }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.url }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.method }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.space }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.headers }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.proxy }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.valid }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">{{ task.timestamp }}</td>
                <td style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">
                    <button type="button" class="btn btn-default">
                        <a href="{{ url_for('task.edit_task', tid=task.id) }}">修改</a>
                    </button>
                    &nbsp;&nbsp;
                    <button type="button" class="btn btn-warning">
                        <a href="{{ url_for('task.delete_task', tid=task.id) }}">删除</a>
                    </button>
                </td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
    </div>
</div>
{% endblock %}